spring.application.name=Surest_Member_Management

spring.datasource.url=jdbc:postgresql://localhost:5432/Surest_Member_management
spring.datasource.username=postgres
spring.datasource.password=test

spring.jpa.hibernate.ddl-auto=update

server.port=8081

jwt.secret=mySuperSecretKeyThatIsAtLeast32BytesLong!
jwt.expiration=3600000