ALTER TABLE IF EXISTS member
    ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0 NOT NULL;

ALTER TABLE IF EXISTS role
    ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0 NOT NULL;

ALTER TABLE IF EXISTS user_table
    ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0 NOT NULL;
